name: "Build"

on:
  push:
    # Build for all branches, but not for tags, there is a separate deploy
    # workflow for tags.
    branches:
      - "*"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3.5.3"

      - name: "Cache PureScript"
        uses: "actions/cache@v3.3.1"
        with:
          path: "app/.spago"
          key: "spago-${{ hashFiles('app/spago.dhall', 'app/packages.dhall', 'flake.lock') }}"
          restore-keys: "spago-"

      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
          install_url: "https://releases.nixos.org/nix/nix-2.17.0/install"

      - name: "Build"
        run: "nix develop --command make"
