name: "Build"

on:
  push:
    # Build for all branches, but not for tags, there is a separate deploy
    # workflow for tags.
    branches:
      - "*"

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"

      - name: "Cache PureScript"
        uses: "actions/cache@v2.0.0"
        with:
          path: "app/.psc-package"
          key: "psc-package-${{ hashFiles('app/psc-package.json', 'nixpkgs-pinned.nix') }}"
          restore-keys: "psc-package-"

      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
          install_url: "https://releases.nixos.org/nix/nix-2.3.7/install"

      - name: "Build"
        run: "nix run -c make"
