name: "Deploy"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3.5.3"

      - name: "Cache PureScript"
        uses: "actions/cache@v3.3.1"
        with:
          path: "app/.spago"
          key: "spago-${{ hashFiles('app/spago.dhall', 'app/packages.dhall', 'flake.lock') }}"
          restore-keys: "spago-"

      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"
          install_url: "https://releases.nixos.org/nix/nix-2.17.0/install"

      - name: "Build"
        run: "nix develop --command make"

      - name: "Deploy"
        uses: "peaceiris/actions-gh-pages@v3.6.1"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "${{ github.ref }}"
          publish_dir: "out"
